# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/[C] Windows 10/Users/samueldrouin/source/repos/GUIDE-CFR/guide/interface/ui/afficher_activite.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AfficherActivite(object):
    def setupUi(self, AfficherActivite):
        AfficherActivite.setObjectName("AfficherActivite")
        AfficherActivite.resize(600, 700)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        AfficherActivite.setFont(font)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(AfficherActivite)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(AfficherActivite)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(AfficherActivite)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(AfficherActivite)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_4 = QtWidgets.QLabel(AfficherActivite)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(AfficherActivite)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtWidgets.QLabel(AfficherActivite)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(AfficherActivite)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txt_nom = QtWidgets.QLineEdit(AfficherActivite)
        self.txt_nom.setReadOnly(True)
        self.txt_nom.setObjectName("txt_nom")
        self.horizontalLayout_3.addWidget(self.txt_nom)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txt_lieu = QtWidgets.QLineEdit(AfficherActivite)
        self.txt_lieu.setReadOnly(True)
        self.txt_lieu.setObjectName("txt_lieu")
        self.horizontalLayout_4.addWidget(self.txt_lieu)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ded_date = QtWidgets.QDateEdit(AfficherActivite)
        self.ded_date.setObjectName("ded_date")
        self.horizontalLayout_5.addWidget(self.ded_date)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ded_limite = QtWidgets.QDateEdit(AfficherActivite)
        self.ded_limite.setObjectName("ded_limite")
        self.horizontalLayout_6.addWidget(self.ded_limite)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ted_heure_debut = QtWidgets.QTimeEdit(AfficherActivite)
        self.ted_heure_debut.setObjectName("ted_heure_debut")
        self.horizontalLayout_7.addWidget(self.ted_heure_debut)
        self.label_9 = QtWidgets.QLabel(AfficherActivite)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.ted_heure_fin = QtWidgets.QTimeEdit(AfficherActivite)
        self.ted_heure_fin.setObjectName("ted_heure_fin")
        self.horizontalLayout_7.addWidget(self.ted_heure_fin)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.txt_responsable = QtWidgets.QLineEdit(AfficherActivite)
        self.txt_responsable.setReadOnly(True)
        self.txt_responsable.setObjectName("txt_responsable")
        self.horizontalLayout_9.addWidget(self.txt_responsable)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.label_10 = QtWidgets.QLabel(AfficherActivite)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.btn_annuler = QtWidgets.QPushButton(AfficherActivite)
        self.btn_annuler.setAutoDefault(False)
        self.btn_annuler.setObjectName("btn_annuler")
        self.horizontalLayout.addWidget(self.btn_annuler)
        self.btn_modifier = QtWidgets.QPushButton(AfficherActivite)
        self.btn_modifier.setAutoDefault(False)
        self.btn_modifier.setObjectName("btn_modifier")
        self.horizontalLayout.addWidget(self.btn_modifier)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(AfficherActivite)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(AfficherActivite)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbl_inscriptions = QtWidgets.QTableWidget(AfficherActivite)
        self.tbl_inscriptions.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_inscriptions.sizePolicy().hasHeightForWidth())
        self.tbl_inscriptions.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.tbl_inscriptions.setPalette(palette)
        self.tbl_inscriptions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_inscriptions.setAlternatingRowColors(True)
        self.tbl_inscriptions.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tbl_inscriptions.setObjectName("tbl_inscriptions")
        self.tbl_inscriptions.setColumnCount(6)
        self.tbl_inscriptions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscriptions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscriptions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscriptions.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscriptions.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscriptions.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscriptions.setHorizontalHeaderItem(5, item)
        self.horizontalLayout_2.addWidget(self.tbl_inscriptions)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_liste = QtWidgets.QPushButton(AfficherActivite)
        self.btn_liste.setAutoDefault(False)
        self.btn_liste.setObjectName("btn_liste")
        self.verticalLayout.addWidget(self.btn_liste)
        self.btn_presence = QtWidgets.QPushButton(AfficherActivite)
        self.btn_presence.setAutoDefault(False)
        self.btn_presence.setObjectName("btn_presence")
        self.verticalLayout.addWidget(self.btn_presence)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(579, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.btn_fermer = QtWidgets.QPushButton(AfficherActivite)
        self.btn_fermer.setDefault(True)
        self.btn_fermer.setObjectName("btn_fermer")
        self.horizontalLayout_8.addWidget(self.btn_fermer)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)

        self.retranslateUi(AfficherActivite)
        QtCore.QMetaObject.connectSlotsByName(AfficherActivite)
        AfficherActivite.setTabOrder(self.ded_date, self.ted_heure_debut)
        AfficherActivite.setTabOrder(self.ted_heure_debut, self.ted_heure_fin)
        AfficherActivite.setTabOrder(self.ted_heure_fin, self.ded_limite)
        AfficherActivite.setTabOrder(self.ded_limite, self.btn_fermer)
        AfficherActivite.setTabOrder(self.btn_fermer, self.btn_annuler)
        AfficherActivite.setTabOrder(self.btn_annuler, self.txt_nom)
        AfficherActivite.setTabOrder(self.txt_nom, self.txt_lieu)
        AfficherActivite.setTabOrder(self.txt_lieu, self.tbl_inscriptions)
        AfficherActivite.setTabOrder(self.tbl_inscriptions, self.btn_modifier)
        AfficherActivite.setTabOrder(self.btn_modifier, self.btn_liste)
        AfficherActivite.setTabOrder(self.btn_liste, self.btn_presence)

    def retranslateUi(self, AfficherActivite):
        _translate = QtCore.QCoreApplication.translate
        AfficherActivite.setWindowTitle(_translate("AfficherActivite", "Activité"))
        self.label.setText(_translate("AfficherActivite", "Activité"))
        self.label_8.setText(_translate("AfficherActivite", "Informations"))
        self.label_7.setText(_translate("AfficherActivite", "Nom : "))
        self.label_4.setText(_translate("AfficherActivite", "Lieu : "))
        self.label_3.setText(_translate("AfficherActivite", "Date : "))
        self.label_5.setText(_translate("AfficherActivite", "Heure : "))
        self.label_6.setText(_translate("AfficherActivite", "Date limite inscription : "))
        self.label_9.setText(_translate("AfficherActivite", "à"))
        self.label_10.setText(_translate("AfficherActivite", "Responsable :"))
        self.btn_annuler.setText(_translate("AfficherActivite", "Annuler l\'activité"))
        self.btn_modifier.setText(_translate("AfficherActivite", "Modifier"))
        self.label_2.setText(_translate("AfficherActivite", "Liste des inscriptions"))
        item = self.tbl_inscriptions.horizontalHeaderItem(0)
        item.setText(_translate("AfficherActivite", "ID_INSCRIPTION"))
        item = self.tbl_inscriptions.horizontalHeaderItem(1)
        item.setText(_translate("AfficherActivite", "Nom"))
        item = self.tbl_inscriptions.horizontalHeaderItem(2)
        item.setText(_translate("AfficherActivite", "Téléphone"))
        item = self.tbl_inscriptions.horizontalHeaderItem(3)
        item.setText(_translate("AfficherActivite", "Membre"))
        item = self.tbl_inscriptions.horizontalHeaderItem(4)
        item.setText(_translate("AfficherActivite", "Payé"))
        item = self.tbl_inscriptions.horizontalHeaderItem(5)
        item.setText(_translate("AfficherActivite", "Présente"))
        self.btn_liste.setText(_translate("AfficherActivite", "Liste de présences"))
        self.btn_presence.setText(_translate("AfficherActivite", "Entrée des présences"))
        self.btn_fermer.setText(_translate("AfficherActivite", "Fermer"))

