# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/[C] Windows 10/Users/samueldrouin/source/repos/GUIDE-CFR/guide/interface/ui/groupe.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Groupe(object):
    def setupUi(self, Groupe):
        Groupe.setObjectName("Groupe")
        Groupe.resize(642, 518)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        Groupe.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Groupe)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Groupe)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Groupe)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txt_activite = QtWidgets.QLineEdit(Groupe)
        self.txt_activite.setObjectName("txt_activite")
        self.horizontalLayout.addWidget(self.txt_activite)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tbl_activite = QtWidgets.QTableWidget(Groupe)
        self.tbl_activite.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_activite.setAlternatingRowColors(True)
        self.tbl_activite.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_activite.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_activite.setObjectName("tbl_activite")
        self.tbl_activite.setColumnCount(4)
        self.tbl_activite.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(3, item)
        self.tbl_activite.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tbl_activite)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(Groupe)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(Groupe)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(Groupe)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.sbx_f_0_4 = QtWidgets.QSpinBox(Groupe)
        self.sbx_f_0_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_f_0_4.setObjectName("sbx_f_0_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbx_f_0_4)
        self.label_7 = QtWidgets.QLabel(Groupe)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_9 = QtWidgets.QLabel(Groupe)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.sbx_f_5_11 = QtWidgets.QSpinBox(Groupe)
        self.sbx_f_5_11.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_f_5_11.setObjectName("sbx_f_5_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbx_f_5_11)
        self.sbx_f_12_17 = QtWidgets.QSpinBox(Groupe)
        self.sbx_f_12_17.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_f_12_17.setObjectName("sbx_f_12_17")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sbx_f_12_17)
        self.label_11 = QtWidgets.QLabel(Groupe)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.sbx_f_18_34 = QtWidgets.QSpinBox(Groupe)
        self.sbx_f_18_34.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_f_18_34.setObjectName("sbx_f_18_34")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sbx_f_18_34)
        self.label_13 = QtWidgets.QLabel(Groupe)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(Groupe)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.sbx_f_35_64 = QtWidgets.QSpinBox(Groupe)
        self.sbx_f_35_64.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_f_35_64.setObjectName("sbx_f_35_64")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sbx_f_35_64)
        self.sbx_f_65 = QtWidgets.QSpinBox(Groupe)
        self.sbx_f_65.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_f_65.setObjectName("sbx_f_65")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sbx_f_65)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.label_4 = QtWidgets.QLabel(Groupe)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.sbx_h_0_4 = QtWidgets.QSpinBox(Groupe)
        self.sbx_h_0_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_h_0_4.setObjectName("sbx_h_0_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbx_h_0_4)
        self.label_8 = QtWidgets.QLabel(Groupe)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.sbx_h_5_11 = QtWidgets.QSpinBox(Groupe)
        self.sbx_h_5_11.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_h_5_11.setObjectName("sbx_h_5_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbx_h_5_11)
        self.label_10 = QtWidgets.QLabel(Groupe)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.sbx_h_12_17 = QtWidgets.QSpinBox(Groupe)
        self.sbx_h_12_17.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_h_12_17.setObjectName("sbx_h_12_17")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sbx_h_12_17)
        self.label_12 = QtWidgets.QLabel(Groupe)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_6 = QtWidgets.QLabel(Groupe)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.sbx_h_18_34 = QtWidgets.QSpinBox(Groupe)
        self.sbx_h_18_34.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_h_18_34.setObjectName("sbx_h_18_34")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sbx_h_18_34)
        self.label_15 = QtWidgets.QLabel(Groupe)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(Groupe)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.sbx_h_35_64 = QtWidgets.QSpinBox(Groupe)
        self.sbx_h_35_64.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_h_35_64.setObjectName("sbx_h_35_64")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sbx_h_35_64)
        self.sbx_h_65 = QtWidgets.QSpinBox(Groupe)
        self.sbx_h_65.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sbx_h_65.setObjectName("sbx_h_65")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sbx_h_65)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_cancel = QtWidgets.QPushButton(Groupe)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_3.addWidget(self.btn_cancel)
        self.btn_add = QtWidgets.QPushButton(Groupe)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_3.addWidget(self.btn_add)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Groupe)
        QtCore.QMetaObject.connectSlotsByName(Groupe)

    def retranslateUi(self, Groupe):
        _translate = QtCore.QCoreApplication.translate
        Groupe.setWindowTitle(_translate("Groupe", "Groupe"))
        self.label.setText(_translate("Groupe", "Groupe non membre"))
        self.label_2.setText(_translate("Groupe", "Activité : "))
        self.txt_activite.setPlaceholderText(_translate("Groupe", "Nom de l\'activité"))
        item = self.tbl_activite.horizontalHeaderItem(0)
        item.setText(_translate("Groupe", "INDEX"))
        item = self.tbl_activite.horizontalHeaderItem(1)
        item.setText(_translate("Groupe", "Nom"))
        item = self.tbl_activite.horizontalHeaderItem(2)
        item.setText(_translate("Groupe", "Date"))
        item = self.tbl_activite.horizontalHeaderItem(3)
        item.setText(_translate("Groupe", "Heure"))
        self.label_3.setText(_translate("Groupe", "Femme"))
        self.label_5.setText(_translate("Groupe", "0 - 4 ans"))
        self.label_7.setText(_translate("Groupe", "5 - 11 ans"))
        self.label_9.setText(_translate("Groupe", "12 - 17 ans"))
        self.label_11.setText(_translate("Groupe", "18 - 34 ans"))
        self.label_13.setText(_translate("Groupe", "35 - 64 ans"))
        self.label_14.setText(_translate("Groupe", "65 + ans"))
        self.label_4.setText(_translate("Groupe", "Homme"))
        self.label_8.setText(_translate("Groupe", "5 - 11 ans"))
        self.label_10.setText(_translate("Groupe", "12 - 17 ans"))
        self.label_12.setText(_translate("Groupe", "18 - 34 ans"))
        self.label_6.setText(_translate("Groupe", "0 - 4 ans"))
        self.label_15.setText(_translate("Groupe", "35 - 64 ans"))
        self.label_16.setText(_translate("Groupe", "65 + ans"))
        self.btn_cancel.setText(_translate("Groupe", "Annuler"))
        self.btn_add.setText(_translate("Groupe", "Ajouter"))

