# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/[C] Windows 10/Users/samueldrouin/source/repos/GUIDE-CFR/guide/interface/ui/inscription_membre.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InscriptionMembre(object):
    def setupUi(self, InscriptionMembre):
        InscriptionMembre.setObjectName("InscriptionMembre")
        InscriptionMembre.resize(440, 384)
        InscriptionMembre.setMinimumSize(QtCore.QSize(440, 384))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        InscriptionMembre.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(InscriptionMembre)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_titre = QtWidgets.QLabel(InscriptionMembre)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titre.setFont(font)
        self.lbl_titre.setObjectName("lbl_titre")
        self.verticalLayout.addWidget(self.lbl_titre)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(InscriptionMembre)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.txt_nom = QtWidgets.QLineEdit(InscriptionMembre)
        self.txt_nom.setReadOnly(True)
        self.txt_nom.setObjectName("txt_nom")
        self.horizontalLayout_3.addWidget(self.txt_nom)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(InscriptionMembre)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.txt_telephone = QtWidgets.QLineEdit(InscriptionMembre)
        self.txt_telephone.setReadOnly(True)
        self.txt_telephone.setObjectName("txt_telephone")
        self.horizontalLayout_4.addWidget(self.txt_telephone)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(InscriptionMembre)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.txt_numero_membre = QtWidgets.QLineEdit(InscriptionMembre)
        self.txt_numero_membre.setReadOnly(True)
        self.txt_numero_membre.setObjectName("txt_numero_membre")
        self.horizontalLayout_6.addWidget(self.txt_numero_membre)
        self.chk_honoraire = QtWidgets.QCheckBox(InscriptionMembre)
        self.chk_honoraire.setObjectName("chk_honoraire")
        self.horizontalLayout_6.addWidget(self.chk_honoraire)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(InscriptionMembre)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.txt_recu = QtWidgets.QLineEdit(InscriptionMembre)
        self.txt_recu.setObjectName("txt_recu")
        self.horizontalLayout_5.addWidget(self.txt_recu)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tbl_commande = QtWidgets.QTableWidget(InscriptionMembre)
        self.tbl_commande.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbl_commande.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_commande.setTabKeyNavigation(False)
        self.tbl_commande.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tbl_commande.setShowGrid(True)
        self.tbl_commande.setRowCount(1)
        self.tbl_commande.setColumnCount(2)
        self.tbl_commande.setObjectName("tbl_commande")
        item = QtWidgets.QTableWidgetItem()
        self.tbl_commande.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbl_commande.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tbl_commande.setItem(0, 1, item)
        self.tbl_commande.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_commande.horizontalHeader().setStretchLastSection(True)
        self.tbl_commande.verticalHeader().setVisible(False)
        self.tbl_commande.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tbl_commande)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(InscriptionMembre)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.txt_total = QtWidgets.QLineEdit(InscriptionMembre)
        self.txt_total.setReadOnly(True)
        self.txt_total.setObjectName("txt_total")
        self.horizontalLayout_2.addWidget(self.txt_total)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_cancel = QtWidgets.QPushButton(InscriptionMembre)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_inscription = QtWidgets.QPushButton(InscriptionMembre)
        self.btn_inscription.setDefault(True)
        self.btn_inscription.setObjectName("btn_inscription")
        self.horizontalLayout.addWidget(self.btn_inscription)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(InscriptionMembre)
        QtCore.QMetaObject.connectSlotsByName(InscriptionMembre)

    def retranslateUi(self, InscriptionMembre):
        _translate = QtCore.QCoreApplication.translate
        InscriptionMembre.setWindowTitle(_translate("InscriptionMembre", "Inscription d\'un membre"))
        self.lbl_titre.setText(_translate("InscriptionMembre", "Inscription d\'un membre"))
        self.label.setText(_translate("InscriptionMembre", "Nom : "))
        self.label_2.setText(_translate("InscriptionMembre", "Numéro de téléphone : "))
        self.label_6.setText(_translate("InscriptionMembre", "Numéro de membre : "))
        self.chk_honoraire.setText(_translate("InscriptionMembre", "Honoraire"))
        self.label_4.setText(_translate("InscriptionMembre", "Numéro de reçu : "))
        self.txt_recu.setPlaceholderText(_translate("InscriptionMembre", "Numéro de reçu"))
        item = self.tbl_commande.horizontalHeaderItem(0)
        item.setText(_translate("InscriptionMembre", "Article"))
        item = self.tbl_commande.horizontalHeaderItem(1)
        item.setText(_translate("InscriptionMembre", "Prix"))
        __sortingEnabled = self.tbl_commande.isSortingEnabled()
        self.tbl_commande.setSortingEnabled(False)
        self.tbl_commande.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("InscriptionMembre", "Total : "))
        self.btn_cancel.setText(_translate("InscriptionMembre", "Annuler"))
        self.btn_inscription.setText(_translate("InscriptionMembre", "Inscription"))

