# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/[C] Windows 10/Users/samueldrouin/source/repos/GUIDE-CFR/guide/interface/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuGestion = QtWidgets.QMenu(self.menubar)
        self.menuGestion.setObjectName("menuGestion")
        self.menuStatistiques = QtWidgets.QMenu(self.menubar)
        self.menuStatistiques.setObjectName("menuStatistiques")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.act_consult_activites = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Resources/activite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_consult_activites.setIcon(icon)
        self.act_consult_activites.setObjectName("act_consult_activites")
        self.act_consult_lieux = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Resources/Lieu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_consult_lieux.setIcon(icon1)
        self.act_consult_lieux.setObjectName("act_consult_lieux")
        self.act_consult_participantes = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Resources/participante.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_consult_participantes.setIcon(icon2)
        self.act_consult_participantes.setObjectName("act_consult_participantes")
        self.act_consult_categorie_activite = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Resources/Type activite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_consult_categorie_activite.setIcon(icon3)
        self.act_consult_categorie_activite.setObjectName("act_consult_categorie_activite")
        self.act_type_activite = QtWidgets.QAction(MainWindow)
        self.act_type_activite.setObjectName("act_type_activite")
        self.act_responsables = QtWidgets.QAction(MainWindow)
        self.act_responsables.setObjectName("act_responsables")
        self.act_inscription = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Resources/Inscription.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_inscription.setIcon(icon4)
        self.act_inscription.setObjectName("act_inscription")
        self.act_facturation = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Resources/Facture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_facturation.setIcon(icon5)
        self.act_facturation.setObjectName("act_facturation")
        self.act_about = QtWidgets.QAction(MainWindow)
        self.act_about.setObjectName("act_about")
        self.act_about_qt = QtWidgets.QAction(MainWindow)
        self.act_about_qt.setObjectName("act_about_qt")
        self.act_reglage = QtWidgets.QAction(MainWindow)
        self.act_reglage.setObjectName("act_reglage")
        self.act_groupe = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Resources/Groupe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_groupe.setIcon(icon6)
        self.act_groupe.setObjectName("act_groupe")
        self.act_statistiques = QtWidgets.QAction(MainWindow)
        self.act_statistiques.setObjectName("act_statistiques")
        self.act_enregistre = QtWidgets.QAction(MainWindow)
        self.act_enregistre.setObjectName("act_enregistre")
        self.menuGestion.addAction(self.act_type_activite)
        self.menuGestion.addAction(self.act_responsables)
        self.menuGestion.addSeparator()
        self.menuGestion.addAction(self.act_reglage)
        self.menuStatistiques.addAction(self.act_statistiques)
        self.menuStatistiques.addSeparator()
        self.menuStatistiques.addAction(self.act_enregistre)
        self.menuAide.addAction(self.act_about)
        self.menuAide.addSeparator()
        self.menuAide.addAction(self.act_about_qt)
        self.menubar.addAction(self.menuGestion.menuAction())
        self.menubar.addAction(self.menuStatistiques.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())
        self.toolBar.addAction(self.act_consult_participantes)
        self.toolBar.addAction(self.act_consult_activites)
        self.toolBar.addAction(self.act_consult_lieux)
        self.toolBar.addAction(self.act_consult_categorie_activite)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.act_inscription)
        self.toolBar.addAction(self.act_facturation)
        self.toolBar.addAction(self.act_groupe)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GUIDE - Centre de femmes du Haut-Richelieu "))
        self.menuGestion.setTitle(_translate("MainWindow", "Gestion"))
        self.menuStatistiques.setTitle(_translate("MainWindow", "Statistiques"))
        self.menuAide.setTitle(_translate("MainWindow", "Aide"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.act_consult_activites.setText(_translate("MainWindow", "Activités"))
        self.act_consult_lieux.setText(_translate("MainWindow", "Lieux"))
        self.act_consult_participantes.setText(_translate("MainWindow", "Participantes"))
        self.act_consult_participantes.setToolTip(_translate("MainWindow", "Consultation des participantes"))
        self.act_consult_categorie_activite.setText(_translate("MainWindow", "Catégorie d\'activité"))
        self.act_consult_categorie_activite.setToolTip(_translate("MainWindow", "Catégorie d\'activité"))
        self.act_type_activite.setText(_translate("MainWindow", "Type d\'activité"))
        self.act_responsables.setText(_translate("MainWindow", "Responsables"))
        self.act_inscription.setText(_translate("MainWindow", "Inscription"))
        self.act_facturation.setText(_translate("MainWindow", "Facturation"))
        self.act_about.setText(_translate("MainWindow", "À propos"))
        self.act_about_qt.setText(_translate("MainWindow", "À propos de Qt"))
        self.act_reglage.setText(_translate("MainWindow", "Réglages"))
        self.act_groupe.setText(_translate("MainWindow", "Groupe"))
        self.act_statistiques.setText(_translate("MainWindow", "Statistiques"))
        self.act_enregistre.setText(_translate("MainWindow", "Enregistrées"))

