# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/[C] Windows 10/Users/samueldrouin/source/repos/GUIDE-CFR/guide/interface/ui/participante.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Participante(object):
    def setupUi(self, Participante):
        Participante.setObjectName("Participante")
        Participante.resize(830, 681)
        Participante.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        Participante.setFont(font)
        self.lbl_title = QtWidgets.QLabel(Participante)
        self.lbl_title.setGeometry(QtCore.QRect(9, 9, 108, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_title.sizePolicy().hasHeightForWidth())
        self.lbl_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.line = QtWidgets.QFrame(Participante)
        self.line.setGeometry(QtCore.QRect(450, 42, 16, 589))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_17 = QtWidgets.QLabel(Participante)
        self.label_17.setGeometry(QtCore.QRect(12, 40, 239, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label = QtWidgets.QLabel(Participante)
        self.label.setGeometry(QtCore.QRect(13, 100, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Participante)
        self.label_3.setGeometry(QtCore.QRect(13, 130, 52, 21))
        self.label_3.setObjectName("label_3")
        self.label_13 = QtWidgets.QLabel(Participante)
        self.label_13.setGeometry(QtCore.QRect(13, 173, 16, 17))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_4 = QtWidgets.QLabel(Participante)
        self.label_4.setGeometry(QtCore.QRect(13, 190, 35, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Participante)
        self.label_5.setGeometry(QtCore.QRect(13, 220, 59, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Participante)
        self.label_6.setGeometry(QtCore.QRect(13, 250, 79, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Participante)
        self.label_7.setGeometry(QtCore.QRect(10, 310, 85, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Participante)
        self.label_8.setGeometry(QtCore.QRect(10, 340, 80, 21))
        self.label_8.setObjectName("label_8")
        self.lbl_annee_naissance = QtWidgets.QLabel(Participante)
        self.lbl_annee_naissance.setGeometry(QtCore.QRect(10, 370, 130, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_annee_naissance.setFont(font)
        self.lbl_annee_naissance.setObjectName("lbl_annee_naissance")
        self.lbl_personne_nourries = QtWidgets.QLabel(Participante)
        self.lbl_personne_nourries.setGeometry(QtCore.QRect(10, 400, 119, 21))
        self.lbl_personne_nourries.setObjectName("lbl_personne_nourries")
        self.lbl_consentement = QtWidgets.QLabel(Participante)
        self.lbl_consentement.setGeometry(QtCore.QRect(10, 430, 132, 21))
        self.lbl_consentement.setObjectName("lbl_consentement")
        self.label_2 = QtWidgets.QLabel(Participante)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 73, 21))
        self.label_2.setObjectName("label_2")
        self.cbx_photo = QtWidgets.QCheckBox(Participante)
        self.cbx_photo.setGeometry(QtCore.QRect(160, 430, 282, 24))
        self.cbx_photo.setObjectName("cbx_photo")
        self.label_12 = QtWidgets.QLabel(Participante)
        self.label_12.setGeometry(QtCore.QRect(13, 280, 56, 21))
        self.label_12.setObjectName("label_12")
        self.cbx_appelation = QtWidgets.QComboBox(Participante)
        self.cbx_appelation.setGeometry(QtCore.QRect(152, 70, 100, 26))
        self.cbx_appelation.setObjectName("cbx_appelation")
        self.cbx_appelation.addItem("")
        self.cbx_appelation.addItem("")
        self.cbx_appelation.addItem("")
        self.cbx_appelation.addItem("")
        self.cbx_appelation.addItem("")
        self.cbx_appelation.addItem("")
        self.cbx_appelation.addItem("")
        self.txt_adresse1 = QtWidgets.QLineEdit(Participante)
        self.txt_adresse1.setGeometry(QtCore.QRect(160, 130, 291, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_adresse1.sizePolicy().hasHeightForWidth())
        self.txt_adresse1.setSizePolicy(sizePolicy)
        self.txt_adresse1.setObjectName("txt_adresse1")
        self.txt_adresse2 = QtWidgets.QLineEdit(Participante)
        self.txt_adresse2.setGeometry(QtCore.QRect(160, 160, 291, 25))
        self.txt_adresse2.setObjectName("txt_adresse2")
        self.txt_ville = QtWidgets.QLineEdit(Participante)
        self.txt_ville.setGeometry(QtCore.QRect(160, 190, 291, 25))
        self.txt_ville.setObjectName("txt_ville")
        self.cbx_province = QtWidgets.QComboBox(Participante)
        self.cbx_province.setGeometry(QtCore.QRect(160, 220, 177, 26))
        self.cbx_province.setObjectName("cbx_province")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.cbx_province.addItem("")
        self.txt_code_postal = QtWidgets.QLineEdit(Participante)
        self.txt_code_postal.setGeometry(QtCore.QRect(160, 250, 141, 25))
        self.txt_code_postal.setObjectName("txt_code_postal")
        self.txt_telephone1 = QtWidgets.QLineEdit(Participante)
        self.txt_telephone1.setGeometry(QtCore.QRect(160, 310, 181, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_telephone1.sizePolicy().hasHeightForWidth())
        self.txt_telephone1.setSizePolicy(sizePolicy)
        self.txt_telephone1.setObjectName("txt_telephone1")
        self.txt_poste1 = QtWidgets.QLineEdit(Participante)
        self.txt_poste1.setGeometry(QtCore.QRect(350, 310, 101, 25))
        self.txt_poste1.setObjectName("txt_poste1")
        self.txt_telephone2 = QtWidgets.QLineEdit(Participante)
        self.txt_telephone2.setGeometry(QtCore.QRect(160, 340, 181, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_telephone2.sizePolicy().hasHeightForWidth())
        self.txt_telephone2.setSizePolicy(sizePolicy)
        self.txt_telephone2.setObjectName("txt_telephone2")
        self.txt_poste2 = QtWidgets.QLineEdit(Participante)
        self.txt_poste2.setGeometry(QtCore.QRect(350, 340, 101, 25))
        self.txt_poste2.setObjectName("txt_poste2")
        self.sbx_annee_naissance = QtWidgets.QSpinBox(Participante)
        self.sbx_annee_naissance.setGeometry(QtCore.QRect(160, 370, 60, 26))
        self.sbx_annee_naissance.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sbx_annee_naissance.setMaximum(3000)
        self.sbx_annee_naissance.setObjectName("sbx_annee_naissance")
        self.sbx_personnes_nourries = QtWidgets.QSpinBox(Participante)
        self.sbx_personnes_nourries.setGeometry(QtCore.QRect(160, 400, 46, 26))
        self.sbx_personnes_nourries.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sbx_personnes_nourries.setProperty("value", 0)
        self.sbx_personnes_nourries.setObjectName("sbx_personnes_nourries")
        self.txt_email = QtWidgets.QLineEdit(Participante)
        self.txt_email.setGeometry(QtCore.QRect(160, 280, 291, 25))
        self.txt_email.setObjectName("txt_email")
        self.txt_prenom = QtWidgets.QLineEdit(Participante)
        self.txt_prenom.setGeometry(QtCore.QRect(160, 100, 141, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_prenom.sizePolicy().hasHeightForWidth())
        self.txt_prenom.setSizePolicy(sizePolicy)
        self.txt_prenom.setObjectName("txt_prenom")
        self.txt_nom = QtWidgets.QLineEdit(Participante)
        self.txt_nom.setGeometry(QtCore.QRect(310, 100, 141, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_nom.sizePolicy().hasHeightForWidth())
        self.txt_nom.setSizePolicy(sizePolicy)
        self.txt_nom.setObjectName("txt_nom")
        self.tbl_transaction = QtWidgets.QTableWidget(Participante)
        self.tbl_transaction.setGeometry(QtCore.QRect(470, 68, 350, 261))
        self.tbl_transaction.setObjectName("tbl_transaction")
        self.tbl_transaction.setColumnCount(3)
        self.tbl_transaction.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_transaction.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_transaction.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_transaction.setHorizontalHeaderItem(2, item)
        self.lbl_transaction = QtWidgets.QLabel(Participante)
        self.lbl_transaction.setGeometry(QtCore.QRect(470, 40, 71, 18))
        self.lbl_transaction.setObjectName("lbl_transaction")
        self.lbl_inscription = QtWidgets.QLabel(Participante)
        self.lbl_inscription.setGeometry(QtCore.QRect(470, 340, 61, 18))
        self.lbl_inscription.setObjectName("lbl_inscription")
        self.tbl_inscription = QtWidgets.QTableWidget(Participante)
        self.tbl_inscription.setGeometry(QtCore.QRect(470, 370, 350, 261))
        self.tbl_inscription.setObjectName("tbl_inscription")
        self.tbl_inscription.setColumnCount(3)
        self.tbl_inscription.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscription.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscription.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscription.setHorizontalHeaderItem(2, item)
        self.lbl_membre = QtWidgets.QLabel(Participante)
        self.lbl_membre.setGeometry(QtCore.QRect(10, 470, 137, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_membre.setFont(font)
        self.lbl_membre.setObjectName("lbl_membre")
        self.btn_cancel = QtWidgets.QPushButton(Participante)
        self.btn_cancel.setGeometry(QtCore.QRect(654, 640, 80, 26))
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_add = QtWidgets.QPushButton(Participante)
        self.btn_add.setGeometry(QtCore.QRect(740, 640, 80, 26))
        self.btn_add.setDefault(True)
        self.btn_add.setObjectName("btn_add")
        self.chk_membre = QtWidgets.QCheckBox(Participante)
        self.chk_membre.setEnabled(True)
        self.chk_membre.setGeometry(QtCore.QRect(17, 499, 74, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chk_membre.setPalette(palette)
        self.chk_membre.setCheckable(True)
        self.chk_membre.setChecked(False)
        self.chk_membre.setObjectName("chk_membre")
        self.lbl_numero_membre = QtWidgets.QLabel(Participante)
        self.lbl_numero_membre.setGeometry(QtCore.QRect(10, 530, 131, 21))
        self.lbl_numero_membre.setObjectName("lbl_numero_membre")
        self.lbl_renouvellement = QtWidgets.QLabel(Participante)
        self.lbl_renouvellement.setGeometry(QtCore.QRect(10, 560, 151, 21))
        self.lbl_renouvellement.setObjectName("lbl_renouvellement")
        self.chk_actif = QtWidgets.QCheckBox(Participante)
        self.chk_actif.setEnabled(False)
        self.chk_actif.setGeometry(QtCore.QRect(312, 500, 52, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chk_actif.setPalette(palette)
        self.chk_actif.setCheckable(True)
        self.chk_actif.setObjectName("chk_actif")
        self.chk_honoraire = QtWidgets.QCheckBox(Participante)
        self.chk_honoraire.setEnabled(False)
        self.chk_honoraire.setGeometry(QtCore.QRect(370, 500, 83, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chk_honoraire.setPalette(palette)
        self.chk_honoraire.setCheckable(True)
        self.chk_honoraire.setTristate(False)
        self.chk_honoraire.setObjectName("chk_honoraire")
        self.ded_renouvellement = QtWidgets.QDateEdit(Participante)
        self.ded_renouvellement.setGeometry(QtCore.QRect(160, 560, 98, 26))
        self.ded_renouvellement.setReadOnly(True)
        self.ded_renouvellement.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ded_renouvellement.setDisplayFormat("dd-MM-yyyy")
        self.ded_renouvellement.setCalendarPopup(False)
        self.ded_renouvellement.setObjectName("ded_renouvellement")
        self.btn_renew = QtWidgets.QPushButton(Participante)
        self.btn_renew.setGeometry(QtCore.QRect(370, 560, 80, 26))
        self.btn_renew.setAutoDefault(False)
        self.btn_renew.setObjectName("btn_renew")
        self.txt_numero_membre = QtWidgets.QLineEdit(Participante)
        self.txt_numero_membre.setGeometry(QtCore.QRect(160, 530, 108, 25))
        self.txt_numero_membre.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_numero_membre.setReadOnly(True)
        self.txt_numero_membre.setObjectName("txt_numero_membre")

        self.retranslateUi(Participante)
        QtCore.QMetaObject.connectSlotsByName(Participante)
        Participante.setTabOrder(self.cbx_appelation, self.txt_prenom)
        Participante.setTabOrder(self.txt_prenom, self.txt_nom)
        Participante.setTabOrder(self.txt_nom, self.txt_adresse1)
        Participante.setTabOrder(self.txt_adresse1, self.txt_adresse2)
        Participante.setTabOrder(self.txt_adresse2, self.txt_ville)
        Participante.setTabOrder(self.txt_ville, self.cbx_province)
        Participante.setTabOrder(self.cbx_province, self.txt_code_postal)
        Participante.setTabOrder(self.txt_code_postal, self.txt_email)
        Participante.setTabOrder(self.txt_email, self.txt_telephone1)
        Participante.setTabOrder(self.txt_telephone1, self.txt_poste1)
        Participante.setTabOrder(self.txt_poste1, self.txt_telephone2)
        Participante.setTabOrder(self.txt_telephone2, self.txt_poste2)
        Participante.setTabOrder(self.txt_poste2, self.sbx_annee_naissance)
        Participante.setTabOrder(self.sbx_annee_naissance, self.sbx_personnes_nourries)
        Participante.setTabOrder(self.sbx_personnes_nourries, self.cbx_photo)
        Participante.setTabOrder(self.cbx_photo, self.btn_add)
        Participante.setTabOrder(self.btn_add, self.btn_cancel)
        Participante.setTabOrder(self.btn_cancel, self.chk_honoraire)
        Participante.setTabOrder(self.chk_honoraire, self.ded_renouvellement)
        Participante.setTabOrder(self.ded_renouvellement, self.chk_actif)
        Participante.setTabOrder(self.chk_actif, self.chk_membre)

    def retranslateUi(self, Participante):
        _translate = QtCore.QCoreApplication.translate
        Participante.setWindowTitle(_translate("Participante", "Participante"))
        self.lbl_title.setText(_translate("Participante", "Participante"))
        self.label_17.setText(_translate("Participante", "Informations sur la participante"))
        self.label.setText(_translate("Participante", "Nom : "))
        self.label_3.setText(_translate("Participante", "Adresse :"))
        self.label_4.setText(_translate("Participante", "Ville : "))
        self.label_5.setText(_translate("Participante", "Province : "))
        self.label_6.setText(_translate("Participante", "Code postal : "))
        self.label_7.setText(_translate("Participante", "Téléphone 1 : "))
        self.label_8.setText(_translate("Participante", "Téléphone 2 : "))
        self.lbl_annee_naissance.setText(_translate("Participante", "Année de naissance : "))
        self.lbl_personne_nourries.setText(_translate("Participante", "Personnes nourries : "))
        self.lbl_consentement.setText(_translate("Participante", "Consentement photo : "))
        self.label_2.setText(_translate("Participante", "Appelation : "))
        self.cbx_photo.setText(_translate("Participante", "La participante consent à être prise en photo"))
        self.label_12.setText(_translate("Participante", "Courriel : "))
        self.cbx_appelation.setItemText(0, _translate("Participante", "Mme."))
        self.cbx_appelation.setItemText(1, _translate("Participante", "M."))
        self.cbx_appelation.setItemText(2, _translate("Participante", "Organisme"))
        self.cbx_appelation.setItemText(3, _translate("Participante", "École"))
        self.cbx_appelation.setItemText(4, _translate("Participante", "Municipalité"))
        self.cbx_appelation.setItemText(5, _translate("Participante", "Employée"))
        self.cbx_appelation.setItemText(6, _translate("Participante", "Autre"))
        self.txt_adresse1.setPlaceholderText(_translate("Participante", "Adresse"))
        self.txt_adresse2.setPlaceholderText(_translate("Participante", "Adresse 2 (facultatif)"))
        self.txt_ville.setPlaceholderText(_translate("Participante", "Ville"))
        self.cbx_province.setItemText(0, _translate("Participante", "Québec"))
        self.cbx_province.setItemText(1, _translate("Participante", "Alberta"))
        self.cbx_province.setItemText(2, _translate("Participante", "Colombie-Britannique"))
        self.cbx_province.setItemText(3, _translate("Participante", "Île-du-Prince-Édouard"))
        self.cbx_province.setItemText(4, _translate("Participante", "Manitoba"))
        self.cbx_province.setItemText(5, _translate("Participante", "Nouveau-Brunswick"))
        self.cbx_province.setItemText(6, _translate("Participante", "Nouvelle-Écosse"))
        self.cbx_province.setItemText(7, _translate("Participante", "Nunavut"))
        self.cbx_province.setItemText(8, _translate("Participante", "Ontario"))
        self.cbx_province.setItemText(9, _translate("Participante", "Saskatchewan"))
        self.cbx_province.setItemText(10, _translate("Participante", "Terre-Neuve-et-Labrador"))
        self.cbx_province.setItemText(11, _translate("Participante", "Territoires du Nord-Ouest"))
        self.cbx_province.setItemText(12, _translate("Participante", "Yukon"))
        self.txt_code_postal.setPlaceholderText(_translate("Participante", "Code postal"))
        self.txt_telephone1.setPlaceholderText(_translate("Participante", "Téléphone 1"))
        self.txt_poste1.setPlaceholderText(_translate("Participante", "Poste"))
        self.txt_telephone2.setPlaceholderText(_translate("Participante", "Téléphone 2 (facultatif)"))
        self.txt_poste2.setPlaceholderText(_translate("Participante", "Poste"))
        self.txt_email.setPlaceholderText(_translate("Participante", "Courriel"))
        self.txt_prenom.setPlaceholderText(_translate("Participante", "Prénom"))
        self.txt_nom.setPlaceholderText(_translate("Participante", "Nom"))
        item = self.tbl_transaction.horizontalHeaderItem(0)
        item.setText(_translate("Participante", "Description"))
        item = self.tbl_transaction.horizontalHeaderItem(1)
        item.setText(_translate("Participante", "Prix"))
        item = self.tbl_transaction.horizontalHeaderItem(2)
        item.setText(_translate("Participante", "Date"))
        self.lbl_transaction.setText(_translate("Participante", "Transactions"))
        self.lbl_inscription.setText(_translate("Participante", "Inscription"))
        item = self.tbl_inscription.horizontalHeaderItem(0)
        item.setText(_translate("Participante", "Nom"))
        item = self.tbl_inscription.horizontalHeaderItem(1)
        item.setText(_translate("Participante", "Date"))
        item = self.tbl_inscription.horizontalHeaderItem(2)
        item.setText(_translate("Participante", "Heure"))
        self.lbl_membre.setText(_translate("Participante", "Status de membre"))
        self.btn_cancel.setText(_translate("Participante", "Annuler"))
        self.btn_add.setText(_translate("Participante", "Ajouter"))
        self.chk_membre.setText(_translate("Participante", "Membre"))
        self.lbl_numero_membre.setText(_translate("Participante", "Numéro de membre :  "))
        self.lbl_renouvellement.setText(_translate("Participante", "Date de renouvellement : "))
        self.chk_actif.setText(_translate("Participante", "Actif"))
        self.chk_honoraire.setStatusTip(_translate("Participante", "Activer le status de membre honoraire pour ce membre."))
        self.chk_honoraire.setText(_translate("Participante", "Honoraire"))
        self.btn_renew.setText(_translate("Participante", "Renouveler"))
        self.txt_numero_membre.setPlaceholderText(_translate("Participante", "Numéro de membre"))

