# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/[C] Windows 10/Users/samueldrouin/source/repos/GUIDE-CFR/guide/interface/ui/categorie_activite.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CategorieActivite(object):
    def setupUi(self, CategorieActivite):
        CategorieActivite.setObjectName("CategorieActivite")
        CategorieActivite.resize(400, 357)
        CategorieActivite.setMinimumSize(QtCore.QSize(400, 357))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        CategorieActivite.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(CategorieActivite)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_titre = QtWidgets.QLabel(CategorieActivite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_titre.sizePolicy().hasHeightForWidth())
        self.lbl_titre.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titre.setFont(font)
        self.lbl_titre.setObjectName("lbl_titre")
        self.verticalLayout.addWidget(self.lbl_titre)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(CategorieActivite)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_nom = QtWidgets.QLineEdit(CategorieActivite)
        self.txt_nom.setObjectName("txt_nom")
        self.horizontalLayout.addWidget(self.txt_nom)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_7 = QtWidgets.QLabel(CategorieActivite)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbx_responsable = QtWidgets.QComboBox(CategorieActivite)
        self.cbx_responsable.setObjectName("cbx_responsable")
        self.horizontalLayout_2.addWidget(self.cbx_responsable)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_8 = QtWidgets.QLabel(CategorieActivite)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbx_type_activite = QtWidgets.QComboBox(CategorieActivite)
        self.cbx_type_activite.setObjectName("cbx_type_activite")
        self.horizontalLayout_3.addWidget(self.cbx_type_activite)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_9 = QtWidgets.QLabel(CategorieActivite)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbx_lieu = QtWidgets.QComboBox(CategorieActivite)
        self.cbx_lieu.setObjectName("cbx_lieu")
        self.horizontalLayout_4.addWidget(self.cbx_lieu)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(CategorieActivite)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sbx_prix_membre = QtWidgets.QDoubleSpinBox(CategorieActivite)
        self.sbx_prix_membre.setFrame(True)
        self.sbx_prix_membre.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sbx_prix_membre.setMaximum(999.99)
        self.sbx_prix_membre.setSingleStep(12.0)
        self.sbx_prix_membre.setObjectName("sbx_prix_membre")
        self.horizontalLayout_6.addWidget(self.sbx_prix_membre)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_4 = QtWidgets.QLabel(CategorieActivite)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sbx_prix_non_membre = QtWidgets.QDoubleSpinBox(CategorieActivite)
        self.sbx_prix_non_membre.setFrame(True)
        self.sbx_prix_non_membre.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sbx_prix_non_membre.setMaximum(999.99)
        self.sbx_prix_non_membre.setSingleStep(12.0)
        self.sbx_prix_non_membre.setObjectName("sbx_prix_non_membre")
        self.horizontalLayout_7.addWidget(self.sbx_prix_non_membre)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_5 = QtWidgets.QLabel(CategorieActivite)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sbx_participante_minimum = QtWidgets.QSpinBox(CategorieActivite)
        self.sbx_participante_minimum.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sbx_participante_minimum.setObjectName("sbx_participante_minimum")
        self.horizontalLayout_8.addWidget(self.sbx_participante_minimum)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_6 = QtWidgets.QLabel(CategorieActivite)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sbx_participantes_maximum = QtWidgets.QSpinBox(CategorieActivite)
        self.sbx_participantes_maximum.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sbx_participantes_maximum.setObjectName("sbx_participantes_maximum")
        self.horizontalLayout_9.addWidget(self.sbx_participantes_maximum)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.btn_cancel = QtWidgets.QPushButton(CategorieActivite)
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_10.addWidget(self.btn_cancel)
        self.btn_add = QtWidgets.QPushButton(CategorieActivite)
        self.btn_add.setDefault(True)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_10.addWidget(self.btn_add)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)

        self.retranslateUi(CategorieActivite)
        QtCore.QMetaObject.connectSlotsByName(CategorieActivite)
        CategorieActivite.setTabOrder(self.txt_nom, self.cbx_responsable)
        CategorieActivite.setTabOrder(self.cbx_responsable, self.cbx_type_activite)
        CategorieActivite.setTabOrder(self.cbx_type_activite, self.cbx_lieu)
        CategorieActivite.setTabOrder(self.cbx_lieu, self.sbx_prix_membre)
        CategorieActivite.setTabOrder(self.sbx_prix_membre, self.sbx_prix_non_membre)
        CategorieActivite.setTabOrder(self.sbx_prix_non_membre, self.sbx_participante_minimum)
        CategorieActivite.setTabOrder(self.sbx_participante_minimum, self.sbx_participantes_maximum)
        CategorieActivite.setTabOrder(self.sbx_participantes_maximum, self.btn_add)
        CategorieActivite.setTabOrder(self.btn_add, self.btn_cancel)

    def retranslateUi(self, CategorieActivite):
        _translate = QtCore.QCoreApplication.translate
        CategorieActivite.setWindowTitle(_translate("CategorieActivite", "Catégorie d\'activité"))
        self.lbl_titre.setText(_translate("CategorieActivite", "Catégorie d\'activité"))
        self.label_2.setText(_translate("CategorieActivite", "Nom : "))
        self.txt_nom.setPlaceholderText(_translate("CategorieActivite", "Nom de la catégorie d\'activité"))
        self.label_7.setText(_translate("CategorieActivite", "Responsable : "))
        self.label_8.setText(_translate("CategorieActivite", "Type d\'activité : "))
        self.label_9.setText(_translate("CategorieActivite", "Lieu : "))
        self.label_3.setText(_translate("CategorieActivite", "Prix membre : "))
        self.label_4.setText(_translate("CategorieActivite", "Prix non membre : "))
        self.label_5.setText(_translate("CategorieActivite", "Participante minimum : "))
        self.label_6.setText(_translate("CategorieActivite", "Participantes maximum : "))
        self.btn_cancel.setText(_translate("CategorieActivite", "Annuler"))
        self.btn_add.setText(_translate("CategorieActivite", "Ajouter"))

