# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/[C] Windows 10/Users/samueldrouin/source/repos/GUIDE-CFR/guide/interface/ui/facturation.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Facturation(object):
    def setupUi(self, Facturation):
        Facturation.setObjectName("Facturation")
        Facturation.resize(1200, 600)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        Facturation.setFont(font)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Facturation)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(Facturation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(Facturation)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.txt_facture = QtWidgets.QLineEdit(Facturation)
        self.txt_facture.setReadOnly(True)
        self.txt_facture.setObjectName("txt_facture")
        self.horizontalLayout_10.addWidget(self.txt_facture)
        self.label_6 = QtWidgets.QLabel(Facturation)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.txt_recu = QtWidgets.QLineEdit(Facturation)
        self.txt_recu.setObjectName("txt_recu")
        self.horizontalLayout_10.addWidget(self.txt_recu)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Facturation)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txt_numero = QtWidgets.QLineEdit(Facturation)
        self.txt_numero.setObjectName("txt_numero")
        self.horizontalLayout.addWidget(self.txt_numero)
        self.chk_actif = QtWidgets.QCheckBox(Facturation)
        self.chk_actif.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chk_actif.setPalette(palette)
        self.chk_actif.setCheckable(True)
        self.chk_actif.setObjectName("chk_actif")
        self.horizontalLayout.addWidget(self.chk_actif)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Facturation)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.txt_nom = QtWidgets.QLineEdit(Facturation)
        self.txt_nom.setReadOnly(True)
        self.txt_nom.setObjectName("txt_nom")
        self.horizontalLayout_2.addWidget(self.txt_nom)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Facturation)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.txt_ville = QtWidgets.QLineEdit(Facturation)
        self.txt_ville.setReadOnly(True)
        self.txt_ville.setObjectName("txt_ville")
        self.horizontalLayout_3.addWidget(self.txt_ville)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(Facturation)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(Facturation)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(Facturation)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.txt_activite = QtWidgets.QLineEdit(Facturation)
        self.txt_activite.setObjectName("txt_activite")
        self.horizontalLayout_5.addWidget(self.txt_activite)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tbl_activite = QtWidgets.QTableWidget(Facturation)
        self.tbl_activite.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_activite.setAlternatingRowColors(True)
        self.tbl_activite.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_activite.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_activite.setObjectName("tbl_activite")
        self.tbl_activite.setColumnCount(6)
        self.tbl_activite.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(5, item)
        self.tbl_activite.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tbl_activite)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.chk_annule = QtWidgets.QCheckBox(Facturation)
        self.chk_annule.setEnabled(False)
        self.chk_annule.setObjectName("chk_annule")
        self.horizontalLayout_8.addWidget(self.chk_annule)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.btn_rembourser = QtWidgets.QPushButton(Facturation)
        self.btn_rembourser.setEnabled(False)
        self.btn_rembourser.setAutoDefault(False)
        self.btn_rembourser.setObjectName("btn_rembourser")
        self.horizontalLayout_7.addWidget(self.btn_rembourser)
        self.btn_ajouter_activite = QtWidgets.QPushButton(Facturation)
        self.btn_ajouter_activite.setEnabled(False)
        self.btn_ajouter_activite.setAutoDefault(False)
        self.btn_ajouter_activite.setObjectName("btn_ajouter_activite")
        self.horizontalLayout_7.addWidget(self.btn_ajouter_activite)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(Facturation)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_11.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(Facturation)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.tbl_inscription = QtWidgets.QTableWidget(Facturation)
        self.tbl_inscription.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_inscription.setAlternatingRowColors(True)
        self.tbl_inscription.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_inscription.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_inscription.setObjectName("tbl_inscription")
        self.tbl_inscription.setColumnCount(5)
        self.tbl_inscription.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscription.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscription.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscription.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscription.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inscription.setHorizontalHeaderItem(4, item)
        self.tbl_inscription.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tbl_inscription)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.btn_ajouter_inscription = QtWidgets.QPushButton(Facturation)
        self.btn_ajouter_inscription.setEnabled(False)
        self.btn_ajouter_inscription.setAutoDefault(False)
        self.btn_ajouter_inscription.setObjectName("btn_ajouter_inscription")
        self.horizontalLayout_9.addWidget(self.btn_ajouter_inscription)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.line_3 = QtWidgets.QFrame(Facturation)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_11.addWidget(self.line_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(Facturation)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.tbl_article = QtWidgets.QTableWidget(Facturation)
        self.tbl_article.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_article.setAlternatingRowColors(True)
        self.tbl_article.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_article.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_article.setObjectName("tbl_article")
        self.tbl_article.setColumnCount(6)
        self.tbl_article.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_article.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_article.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_article.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_article.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_article.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_article.setHorizontalHeaderItem(5, item)
        self.tbl_article.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tbl_article)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.label_10 = QtWidgets.QLabel(Facturation)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.txt_total = QtWidgets.QLineEdit(Facturation)
        self.txt_total.setReadOnly(True)
        self.txt_total.setObjectName("txt_total")
        self.horizontalLayout_4.addWidget(self.txt_total)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.btn_remove = QtWidgets.QPushButton(Facturation)
        self.btn_remove.setEnabled(False)
        self.btn_remove.setAutoDefault(False)
        self.btn_remove.setObjectName("btn_remove")
        self.horizontalLayout_12.addWidget(self.btn_remove)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.btn_annuler = QtWidgets.QPushButton(Facturation)
        self.btn_annuler.setAutoDefault(False)
        self.btn_annuler.setObjectName("btn_annuler")
        self.horizontalLayout_6.addWidget(self.btn_annuler)
        self.btn_enregistrer = QtWidgets.QPushButton(Facturation)
        self.btn_enregistrer.setAutoDefault(False)
        self.btn_enregistrer.setObjectName("btn_enregistrer")
        self.horizontalLayout_6.addWidget(self.btn_enregistrer)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Facturation)
        QtCore.QMetaObject.connectSlotsByName(Facturation)
        Facturation.setTabOrder(self.txt_numero, self.txt_activite)
        Facturation.setTabOrder(self.txt_activite, self.btn_ajouter_activite)
        Facturation.setTabOrder(self.btn_ajouter_activite, self.btn_enregistrer)
        Facturation.setTabOrder(self.btn_enregistrer, self.btn_annuler)
        Facturation.setTabOrder(self.btn_annuler, self.btn_rembourser)
        Facturation.setTabOrder(self.btn_rembourser, self.txt_nom)
        Facturation.setTabOrder(self.txt_nom, self.txt_total)
        Facturation.setTabOrder(self.txt_total, self.chk_actif)
        Facturation.setTabOrder(self.chk_actif, self.txt_ville)
        Facturation.setTabOrder(self.txt_ville, self.txt_facture)
        Facturation.setTabOrder(self.txt_facture, self.btn_ajouter_inscription)
        Facturation.setTabOrder(self.btn_ajouter_inscription, self.txt_recu)
        Facturation.setTabOrder(self.txt_recu, self.tbl_activite)
        Facturation.setTabOrder(self.tbl_activite, self.tbl_inscription)
        Facturation.setTabOrder(self.tbl_inscription, self.tbl_article)
        Facturation.setTabOrder(self.tbl_article, self.btn_remove)

    def retranslateUi(self, Facturation):
        _translate = QtCore.QCoreApplication.translate
        Facturation.setWindowTitle(_translate("Facturation", "Facturation"))
        self.label.setText(_translate("Facturation", "Facturation"))
        self.label_11.setText(_translate("Facturation", "Numéro de la facture : "))
        self.label_6.setText(_translate("Facturation", "Numéro du reçu : "))
        self.txt_recu.setPlaceholderText(_translate("Facturation", "Numéro du reçu"))
        self.label_2.setStatusTip(_translate("Facturation", "Numéro de membre ou de téléphone du participant"))
        self.label_2.setText(_translate("Facturation", "Numéro de participant : "))
        self.txt_numero.setPlaceholderText(_translate("Facturation", "Numéro de téléphone"))
        self.chk_actif.setStatusTip(_translate("Facturation", "Le membre est actif seulement si cette case est sélectionnée"))
        self.chk_actif.setText(_translate("Facturation", "Membre actif"))
        self.label_3.setStatusTip(_translate("Facturation", "Information à titre indicative seulement"))
        self.label_3.setText(_translate("Facturation", "Nom : "))
        self.txt_nom.setPlaceholderText(_translate("Facturation", "Nom"))
        self.label_4.setText(_translate("Facturation", "Ville : "))
        self.txt_ville.setStatusTip(_translate("Facturation", "Information à titre indicative seulement"))
        self.txt_ville.setPlaceholderText(_translate("Facturation", "Ville"))
        self.label_5.setText(_translate("Facturation", "Ajout d\'une activité"))
        self.label_7.setText(_translate("Facturation", "Nom de l\'activité : "))
        self.txt_activite.setPlaceholderText(_translate("Facturation", "Nom de l\'activité"))
        item = self.tbl_activite.horizontalHeaderItem(0)
        item.setText(_translate("Facturation", "INDEX"))
        item = self.tbl_activite.horizontalHeaderItem(1)
        item.setText(_translate("Facturation", "FULL"))
        item = self.tbl_activite.horizontalHeaderItem(2)
        item.setText(_translate("Facturation", "Nom"))
        item = self.tbl_activite.horizontalHeaderItem(3)
        item.setText(_translate("Facturation", "Prix"))
        item = self.tbl_activite.horizontalHeaderItem(4)
        item.setText(_translate("Facturation", "Date"))
        item = self.tbl_activite.horizontalHeaderItem(5)
        item.setText(_translate("Facturation", "Heure"))
        self.chk_annule.setText(_translate("Facturation", "Afficher les activités annulées seulement"))
        self.btn_rembourser.setText(_translate("Facturation", "Rembourser"))
        self.btn_ajouter_activite.setText(_translate("Facturation", "Ajouter"))
        self.label_8.setText(_translate("Facturation", "Inscriptions"))
        item = self.tbl_inscription.horizontalHeaderItem(0)
        item.setText(_translate("Facturation", "INDEX"))
        item = self.tbl_inscription.horizontalHeaderItem(1)
        item.setText(_translate("Facturation", "Nom"))
        item = self.tbl_inscription.horizontalHeaderItem(2)
        item.setText(_translate("Facturation", "Prix"))
        item = self.tbl_inscription.horizontalHeaderItem(3)
        item.setText(_translate("Facturation", "Date"))
        item = self.tbl_inscription.horizontalHeaderItem(4)
        item.setText(_translate("Facturation", "Heure"))
        self.btn_ajouter_inscription.setText(_translate("Facturation", "Ajouter"))
        self.label_9.setText(_translate("Facturation", "Facture"))
        item = self.tbl_article.horizontalHeaderItem(0)
        item.setText(_translate("Facturation", "INDEX"))
        item = self.tbl_article.horizontalHeaderItem(1)
        item.setText(_translate("Facturation", "Nom"))
        item = self.tbl_article.horizontalHeaderItem(2)
        item.setText(_translate("Facturation", "Prix"))
        item = self.tbl_article.horizontalHeaderItem(3)
        item.setText(_translate("Facturation", "Date"))
        item = self.tbl_article.horizontalHeaderItem(4)
        item.setText(_translate("Facturation", "Heure"))
        item = self.tbl_article.horizontalHeaderItem(5)
        item.setText(_translate("Facturation", "Quantité"))
        self.label_10.setText(_translate("Facturation", "Total : "))
        self.btn_remove.setText(_translate("Facturation", "Retirer"))
        self.btn_annuler.setText(_translate("Facturation", "Annuler"))
        self.btn_enregistrer.setText(_translate("Facturation", "Enregistrer"))

