# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/[C] Windows 10/Users/samueldrouin/source/repos/GUIDE-CFR/guide/interface/ui/inscription.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Inscription(object):
    def setupUi(self, Inscription):
        Inscription.setObjectName("Inscription")
        Inscription.resize(800, 500)
        Inscription.setMinimumSize(QtCore.QSize(800, 500))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        Inscription.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Inscription)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Inscription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Inscription)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txt_numero = QtWidgets.QLineEdit(Inscription)
        self.txt_numero.setObjectName("txt_numero")
        self.horizontalLayout.addWidget(self.txt_numero)
        self.chk_actif = QtWidgets.QCheckBox(Inscription)
        self.chk_actif.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chk_actif.setPalette(palette)
        self.chk_actif.setCheckable(True)
        self.chk_actif.setObjectName("chk_actif")
        self.horizontalLayout.addWidget(self.chk_actif)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Inscription)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.txt_nom = QtWidgets.QLineEdit(Inscription)
        self.txt_nom.setReadOnly(True)
        self.txt_nom.setObjectName("txt_nom")
        self.horizontalLayout_2.addWidget(self.txt_nom)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Inscription)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.txt_ville = QtWidgets.QLineEdit(Inscription)
        self.txt_ville.setReadOnly(True)
        self.txt_ville.setObjectName("txt_ville")
        self.horizontalLayout_3.addWidget(self.txt_ville)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(Inscription)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(Inscription)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(Inscription)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.txt_activite = QtWidgets.QLineEdit(Inscription)
        self.txt_activite.setObjectName("txt_activite")
        self.horizontalLayout_4.addWidget(self.txt_activite)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tbl_activite = QtWidgets.QTableWidget(Inscription)
        self.tbl_activite.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_activite.setAlternatingRowColors(True)
        self.tbl_activite.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_activite.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_activite.setObjectName("tbl_activite")
        self.tbl_activite.setColumnCount(6)
        self.tbl_activite.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_activite.setHorizontalHeaderItem(5, item)
        self.tbl_activite.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tbl_activite)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.btn_ajouter = QtWidgets.QPushButton(Inscription)
        self.btn_ajouter.setEnabled(False)
        self.btn_ajouter.setAutoDefault(False)
        self.btn_ajouter.setObjectName("btn_ajouter")
        self.horizontalLayout_5.addWidget(self.btn_ajouter)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(Inscription)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(Inscription)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.tbl_panier = QtWidgets.QTableWidget(Inscription)
        self.tbl_panier.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_panier.setAlternatingRowColors(True)
        self.tbl_panier.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_panier.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_panier.setObjectName("tbl_panier")
        self.tbl_panier.setColumnCount(7)
        self.tbl_panier.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_panier.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_panier.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_panier.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_panier.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_panier.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_panier.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_panier.setHorizontalHeaderItem(6, item)
        self.tbl_panier.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tbl_panier)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.btn_remove = QtWidgets.QPushButton(Inscription)
        self.btn_remove.setEnabled(False)
        self.btn_remove.setAutoDefault(False)
        self.btn_remove.setObjectName("btn_remove")
        self.horizontalLayout_8.addWidget(self.btn_remove)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.btn_annuler = QtWidgets.QPushButton(Inscription)
        self.btn_annuler.setAutoDefault(False)
        self.btn_annuler.setObjectName("btn_annuler")
        self.horizontalLayout_6.addWidget(self.btn_annuler)
        self.btn_enregistrer = QtWidgets.QPushButton(Inscription)
        self.btn_enregistrer.setAutoDefault(False)
        self.btn_enregistrer.setDefault(False)
        self.btn_enregistrer.setObjectName("btn_enregistrer")
        self.horizontalLayout_6.addWidget(self.btn_enregistrer)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Inscription)
        QtCore.QMetaObject.connectSlotsByName(Inscription)
        Inscription.setTabOrder(self.txt_numero, self.txt_activite)
        Inscription.setTabOrder(self.txt_activite, self.btn_ajouter)
        Inscription.setTabOrder(self.btn_ajouter, self.btn_enregistrer)
        Inscription.setTabOrder(self.btn_enregistrer, self.chk_actif)
        Inscription.setTabOrder(self.chk_actif, self.btn_annuler)
        Inscription.setTabOrder(self.btn_annuler, self.txt_ville)
        Inscription.setTabOrder(self.txt_ville, self.txt_nom)

    def retranslateUi(self, Inscription):
        _translate = QtCore.QCoreApplication.translate
        Inscription.setWindowTitle(_translate("Inscription", "Inscription"))
        self.label.setText(_translate("Inscription", "Inscription"))
        self.label_2.setStatusTip(_translate("Inscription", "Numéro de membre ou de téléphone du participant"))
        self.label_2.setText(_translate("Inscription", "Numéro de participant : "))
        self.txt_numero.setPlaceholderText(_translate("Inscription", "Numéro de téléphone"))
        self.chk_actif.setStatusTip(_translate("Inscription", "Le membre est actif seulement si cette case est sélectionnée"))
        self.chk_actif.setText(_translate("Inscription", "Membre actif"))
        self.label_3.setStatusTip(_translate("Inscription", "Information à titre indicative seulement"))
        self.label_3.setText(_translate("Inscription", "Nom : "))
        self.txt_nom.setPlaceholderText(_translate("Inscription", "Nom"))
        self.label_4.setText(_translate("Inscription", "Ville : "))
        self.txt_ville.setStatusTip(_translate("Inscription", "Information à titre indicative seulement"))
        self.txt_ville.setPlaceholderText(_translate("Inscription", "Ville"))
        self.label_5.setText(_translate("Inscription", "Ajout d\'une activité : "))
        self.label_7.setText(_translate("Inscription", "Nom de l\'activité : "))
        self.txt_activite.setPlaceholderText(_translate("Inscription", "Nom de l\'activité"))
        item = self.tbl_activite.horizontalHeaderItem(0)
        item.setText(_translate("Inscription", "INDEX"))
        item = self.tbl_activite.horizontalHeaderItem(1)
        item.setText(_translate("Inscription", "FULL"))
        item = self.tbl_activite.horizontalHeaderItem(2)
        item.setText(_translate("Inscription", "Nom"))
        item = self.tbl_activite.horizontalHeaderItem(3)
        item.setText(_translate("Inscription", "Prix"))
        item = self.tbl_activite.horizontalHeaderItem(4)
        item.setText(_translate("Inscription", "Date"))
        item = self.tbl_activite.horizontalHeaderItem(5)
        item.setText(_translate("Inscription", "Heure"))
        self.btn_ajouter.setText(_translate("Inscription", "Ajouter"))
        self.label_6.setText(_translate("Inscription", "Panier : "))
        item = self.tbl_panier.horizontalHeaderItem(0)
        item.setText(_translate("Inscription", "INDEX"))
        item = self.tbl_panier.horizontalHeaderItem(1)
        item.setText(_translate("Inscription", "STATUS"))
        item = self.tbl_panier.horizontalHeaderItem(2)
        item.setText(_translate("Inscription", "FULL"))
        item = self.tbl_panier.horizontalHeaderItem(3)
        item.setText(_translate("Inscription", "Nom"))
        item = self.tbl_panier.horizontalHeaderItem(4)
        item.setText(_translate("Inscription", "Prix"))
        item = self.tbl_panier.horizontalHeaderItem(5)
        item.setText(_translate("Inscription", "Date"))
        item = self.tbl_panier.horizontalHeaderItem(6)
        item.setText(_translate("Inscription", "Heure"))
        self.btn_remove.setText(_translate("Inscription", "Retirer"))
        self.btn_annuler.setText(_translate("Inscription", "Annuler"))
        self.btn_enregistrer.setText(_translate("Inscription", "Enregistrer"))

