# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/[C] Windows 10/Users/samueldrouin/source/repos/GUIDE-CFR/guide/interface/ui/preparation_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PreparationWizard(object):
    def setupUi(self, PreparationWizard):
        PreparationWizard.setObjectName("PreparationWizard")
        PreparationWizard.resize(619, 442)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        PreparationWizard.setFont(font)
        PreparationWizard.setWizardStyle(QtWidgets.QWizard.ClassicStyle)
        PreparationWizard.setOptions(QtWidgets.QWizard.NoCancelButton|QtWidgets.QWizard.NoDefaultButton)
        self.pgs_description = QtWidgets.QWizardPage()
        self.pgs_description.setObjectName("pgs_description")
        self.img_banniere = QtWidgets.QGraphicsView(self.pgs_description)
        self.img_banniere.setGeometry(QtCore.QRect(0, 0, 281, 91))
        self.img_banniere.setStyleSheet("background: transparent")
        self.img_banniere.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.img_banniere.setFrameShadow(QtWidgets.QFrame.Plain)
        self.img_banniere.setLineWidth(1)
        self.img_banniere.setInteractive(False)
        self.img_banniere.setObjectName("img_banniere")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.pgs_description)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 90, 591, 201))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background: transparent")
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        PreparationWizard.addPage(self.pgs_description)
        self.pgs_selection = QtWidgets.QWizardPage()
        self.pgs_selection.setObjectName("pgs_selection")
        self.rbt_nouvelle_db = QtWidgets.QRadioButton(self.pgs_selection)
        self.rbt_nouvelle_db.setGeometry(QtCore.QRect(30, 40, 191, 20))
        self.rbt_nouvelle_db.setChecked(True)
        self.rbt_nouvelle_db.setObjectName("rbt_nouvelle_db")
        self.rbt_db_existante = QtWidgets.QRadioButton(self.pgs_selection)
        self.rbt_db_existante.setGeometry(QtCore.QRect(30, 70, 191, 20))
        self.rbt_db_existante.setObjectName("rbt_db_existante")
        self.label = QtWidgets.QLabel(self.pgs_selection)
        self.label.setGeometry(QtCore.QRect(0, 10, 571, 16))
        self.label.setObjectName("label")
        self.lbl_emplacement_db = QtWidgets.QLabel(self.pgs_selection)
        self.lbl_emplacement_db.setGeometry(QtCore.QRect(0, 100, 241, 26))
        self.lbl_emplacement_db.setMinimumSize(QtCore.QSize(210, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_emplacement_db.setFont(font)
        self.lbl_emplacement_db.setObjectName("lbl_emplacement_db")
        self.layoutWidget = QtWidgets.QWidget(self.pgs_selection)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 200, 571, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_emplacement_stats = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_emplacement_stats.setReadOnly(True)
        self.txt_emplacement_stats.setObjectName("txt_emplacement_stats")
        self.horizontalLayout_2.addWidget(self.txt_emplacement_stats)
        self.btn_emplacement_stats = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_emplacement_stats.setObjectName("btn_emplacement_stats")
        self.horizontalLayout_2.addWidget(self.btn_emplacement_stats)
        self.lbl_emplacement_parametres = QtWidgets.QLabel(self.pgs_selection)
        self.lbl_emplacement_parametres.setGeometry(QtCore.QRect(0, 170, 271, 26))
        self.lbl_emplacement_parametres.setMinimumSize(QtCore.QSize(210, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_emplacement_parametres.setFont(font)
        self.lbl_emplacement_parametres.setObjectName("lbl_emplacement_parametres")
        self.layoutWidget1 = QtWidgets.QWidget(self.pgs_selection)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 130, 571, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_emplacement_db = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_emplacement_db.setReadOnly(True)
        self.txt_emplacement_db.setObjectName("txt_emplacement_db")
        self.horizontalLayout.addWidget(self.txt_emplacement_db)
        self.btn_emplacement_db = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_emplacement_db.setObjectName("btn_emplacement_db")
        self.horizontalLayout.addWidget(self.btn_emplacement_db)
        PreparationWizard.addPage(self.pgs_selection)
        self.pgs_informations = QtWidgets.QWizardPage()
        self.pgs_informations.setObjectName("pgs_informations")
        self.formLayoutWidget = QtWidgets.QWidget(self.pgs_informations)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 471, 308))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_nom = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_nom.setObjectName("txt_nom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_nom)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txt_departement = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_departement.setObjectName("txt_departement")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_departement)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txt_adresse_1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_adresse_1.setObjectName("txt_adresse_1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_adresse_1)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txt_adresse_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_adresse_2.setObjectName("txt_adresse_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_adresse_2)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txt_ville = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_ville.setObjectName("txt_ville")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_ville)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.txt_code_postal = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_code_postal.setObjectName("txt_code_postal")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_code_postal)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.txt_province = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_province.setObjectName("txt_province")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_province)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.txt_pays = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_pays.setObjectName("txt_pays")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txt_pays)
        PreparationWizard.addPage(self.pgs_informations)
        self.pgs_contact = QtWidgets.QWizardPage()
        self.pgs_contact.setObjectName("pgs_contact")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.pgs_contact)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 471, 308))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txt_poste = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_poste.setObjectName("txt_poste")
        self.horizontalLayout_5.addWidget(self.txt_poste)
        self.txt_telephone = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_telephone.setObjectName("txt_telephone")
        self.horizontalLayout_5.addWidget(self.txt_telephone)
        self.horizontalLayout_5.setStretch(0, 1)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.txt_courriel = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_courriel.setObjectName("txt_courriel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_courriel)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.txt_poste_sf = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_poste_sf.setObjectName("txt_poste_sf")
        self.horizontalLayout_6.addWidget(self.txt_poste_sf)
        self.txt_sf = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_sf.setObjectName("txt_sf")
        self.horizontalLayout_6.addWidget(self.txt_sf)
        self.horizontalLayout_6.setStretch(0, 1)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.txt_poste_fax = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_poste_fax.setObjectName("txt_poste_fax")
        self.horizontalLayout_7.addWidget(self.txt_poste_fax)
        self.txt_fax = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_fax.setObjectName("txt_fax")
        self.horizontalLayout_7.addWidget(self.txt_fax)
        self.horizontalLayout_7.setStretch(0, 1)
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        PreparationWizard.addPage(self.pgs_contact)
        self.pgs_module = QtWidgets.QWizardPage()
        self.pgs_module.setObjectName("pgs_module")
        self.groupBox = QtWidgets.QGroupBox(self.pgs_module)
        self.groupBox.setGeometry(QtCore.QRect(180, 40, 113, 125))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chk_article = QtWidgets.QCheckBox(self.groupBox)
        self.chk_article.setObjectName("chk_article")
        self.verticalLayout_2.addWidget(self.chk_article)
        self.chk_facturation = QtWidgets.QCheckBox(self.groupBox)
        self.chk_facturation.setObjectName("chk_facturation")
        self.verticalLayout_2.addWidget(self.chk_facturation)
        self.chk_inscription = QtWidgets.QCheckBox(self.groupBox)
        self.chk_inscription.setObjectName("chk_inscription")
        self.verticalLayout_2.addWidget(self.chk_inscription)
        self.chk_groupe = QtWidgets.QCheckBox(self.groupBox)
        self.chk_groupe.setObjectName("chk_groupe")
        self.verticalLayout_2.addWidget(self.chk_groupe)
        self.groupBox_2 = QtWidgets.QGroupBox(self.pgs_module)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 40, 162, 146))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chk_activite = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_activite.setCheckable(True)
        self.chk_activite.setChecked(False)
        self.chk_activite.setObjectName("chk_activite")
        self.verticalLayout.addWidget(self.chk_activite)
        self.chk_categorie_activite = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_categorie_activite.setObjectName("chk_categorie_activite")
        self.verticalLayout.addWidget(self.chk_categorie_activite)
        self.chk_lieu = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_lieu.setObjectName("chk_lieu")
        self.verticalLayout.addWidget(self.chk_lieu)
        self.chk_responsable = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_responsable.setObjectName("chk_responsable")
        self.verticalLayout.addWidget(self.chk_responsable)
        self.chk_type_activite = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_type_activite.setObjectName("chk_type_activite")
        self.verticalLayout.addWidget(self.chk_type_activite)
        self.groupBox_3 = QtWidgets.QGroupBox(self.pgs_module)
        self.groupBox_3.setGeometry(QtCore.QRect(310, 40, 117, 83))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chk_membre = QtWidgets.QCheckBox(self.groupBox_3)
        self.chk_membre.setObjectName("chk_membre")
        self.verticalLayout_3.addWidget(self.chk_membre)
        self.chk_partitipante = QtWidgets.QCheckBox(self.groupBox_3)
        self.chk_partitipante.setObjectName("chk_partitipante")
        self.verticalLayout_3.addWidget(self.chk_partitipante)
        self.chk_tout = QtWidgets.QCheckBox(self.pgs_module)
        self.chk_tout.setGeometry(QtCore.QRect(0, 10, 151, 20))
        self.chk_tout.setCheckable(True)
        self.chk_tout.setChecked(False)
        self.chk_tout.setObjectName("chk_tout")
        PreparationWizard.addPage(self.pgs_module)
        self.pgs_fin = QtWidgets.QWizardPage()
        self.pgs_fin.setObjectName("pgs_fin")
        self.img_copyrights = QtWidgets.QGraphicsView(self.pgs_fin)
        self.img_copyrights.setGeometry(QtCore.QRect(280, 50, 311, 101))
        self.img_copyrights.setStyleSheet("background: transparent")
        self.img_copyrights.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.img_copyrights.setFrameShadow(QtWidgets.QFrame.Plain)
        self.img_copyrights.setLineWidth(1)
        self.img_copyrights.setInteractive(False)
        self.img_copyrights.setObjectName("img_copyrights")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.pgs_fin)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(0, 0, 591, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("background: transparent")
        self.plainTextEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        PreparationWizard.addPage(self.pgs_fin)

        self.retranslateUi(PreparationWizard)
        QtCore.QMetaObject.connectSlotsByName(PreparationWizard)

    def retranslateUi(self, PreparationWizard):
        _translate = QtCore.QCoreApplication.translate
        PreparationWizard.setWindowTitle(_translate("PreparationWizard", "Installation de GUIDE"))
        self.pgs_description.setTitle(_translate("PreparationWizard", "Préparation du programme GUIDE"))
        self.pgs_description.setSubTitle(_translate("PreparationWizard", "Cet assistant vous guidera dans les étapes nécessaires pour compléter l\'installation du programme GUIDE sur votre ordinateur. "))
        self.plainTextEdit.setPlainText(_translate("PreparationWizard", "Bienvenu dans le programme GUIDE. Cet assistant vous guidera des les étapes nécessaire pour préparer le programme à sa première utilisation. \n"
"\n"
"Si une base de donnée existe déjà, vous n\'aurez qu\'à la sélectionner pour pouvoir commencer à utiliser le programme. \n"
"\n"
"Sinon, il sera nécessaire d\'un créer une. Cet assistant vous guidera dans ces étapes : \n"
"\n"
"    1) Création de la base de données\n"
"    2) Sélection des modules à installer"))
        self.pgs_selection.setTitle(_translate("PreparationWizard", "Sélection de la base de données"))
        self.pgs_selection.setSubTitle(_translate("PreparationWizard", "Sélection d\'une base de données existante ou création d\'une nouvelle. "))
        self.rbt_nouvelle_db.setText(_translate("PreparationWizard", "Nouvelle base de donnée"))
        self.rbt_db_existante.setText(_translate("PreparationWizard", "Base de donnée existante"))
        self.label.setText(_translate("PreparationWizard", "Veuillez indiquer s\'il existe déjà une base de données GUIDE ou s\'il faut en créer une nouvelle"))
        self.lbl_emplacement_db.setText(_translate("PreparationWizard", "Emplacement de la base de données : "))
        self.btn_emplacement_stats.setText(_translate("PreparationWizard", "Parcourir..."))
        self.lbl_emplacement_parametres.setText(_translate("PreparationWizard", "Dossier des statistiques : "))
        self.btn_emplacement_db.setText(_translate("PreparationWizard", "Parcourir..."))
        self.pgs_informations.setTitle(_translate("PreparationWizard", "Information sur l\'entreprise"))
        self.pgs_informations.setSubTitle(_translate("PreparationWizard", "Entrez les informations sur l\'entreprise. Elle serviront lors de la création de factures ainsi que pour les rapports. Ces informations pourront être modifiées par la suite."))
        self.label_2.setText(_translate("PreparationWizard", "Nom de l\'entreprise : "))
        self.txt_nom.setPlaceholderText(_translate("PreparationWizard", "Nom de l\'entreprise"))
        self.label_3.setText(_translate("PreparationWizard", "Département : "))
        self.txt_departement.setPlaceholderText(_translate("PreparationWizard", "Département"))
        self.label_4.setText(_translate("PreparationWizard", "Adresse 1 : "))
        self.txt_adresse_1.setPlaceholderText(_translate("PreparationWizard", "Adresse ligne 1"))
        self.label_5.setText(_translate("PreparationWizard", "Adresse 2 : "))
        self.txt_adresse_2.setPlaceholderText(_translate("PreparationWizard", "Adresse ligne 2"))
        self.label_6.setText(_translate("PreparationWizard", "Ville : "))
        self.txt_ville.setPlaceholderText(_translate("PreparationWizard", "Ville"))
        self.label_7.setText(_translate("PreparationWizard", "Code postal : "))
        self.txt_code_postal.setPlaceholderText(_translate("PreparationWizard", "Code postal"))
        self.label_8.setText(_translate("PreparationWizard", "Province : "))
        self.txt_province.setPlaceholderText(_translate("PreparationWizard", "Province"))
        self.label_9.setText(_translate("PreparationWizard", "Pays : "))
        self.txt_pays.setPlaceholderText(_translate("PreparationWizard", "Pays"))
        self.pgs_contact.setTitle(_translate("PreparationWizard", "Informations de contact"))
        self.pgs_contact.setSubTitle(_translate("PreparationWizard", "Entrez les informations de contact de l\'entreprise. Elle serviront lors de la création de factures ainsi que pour les rapports. Ces informations pourront être modifiées par la suite."))
        self.label_29.setText(_translate("PreparationWizard", "Téléphone : "))
        self.txt_poste.setPlaceholderText(_translate("PreparationWizard", "Téléphone"))
        self.txt_telephone.setPlaceholderText(_translate("PreparationWizard", "Poste"))
        self.label_28.setText(_translate("PreparationWizard", "Courriel : "))
        self.txt_courriel.setPlaceholderText(_translate("PreparationWizard", "Courriel"))
        self.label_30.setText(_translate("PreparationWizard", "Sans frais : "))
        self.label_31.setText(_translate("PreparationWizard", "Fax : "))
        self.txt_poste_sf.setPlaceholderText(_translate("PreparationWizard", "Téléphone"))
        self.txt_sf.setPlaceholderText(_translate("PreparationWizard", "Poste"))
        self.txt_poste_fax.setPlaceholderText(_translate("PreparationWizard", "Téléphone"))
        self.txt_fax.setPlaceholderText(_translate("PreparationWizard", "Poste"))
        self.pgs_module.setTitle(_translate("PreparationWizard", "Installation des modules"))
        self.pgs_module.setSubTitle(_translate("PreparationWizard", "Veuillez sélectionner les modules à installer dans la base de donnée."))
        self.groupBox.setTitle(_translate("PreparationWizard", "Facturation"))
        self.chk_article.setText(_translate("PreparationWizard", "Article"))
        self.chk_facturation.setText(_translate("PreparationWizard", "Facturation"))
        self.chk_inscription.setText(_translate("PreparationWizard", "Inscription"))
        self.chk_groupe.setText(_translate("PreparationWizard", "Groupe"))
        self.groupBox_2.setTitle(_translate("PreparationWizard", "Activité"))
        self.chk_activite.setText(_translate("PreparationWizard", "Activité"))
        self.chk_categorie_activite.setText(_translate("PreparationWizard", "Catégorie d\'activité"))
        self.chk_lieu.setText(_translate("PreparationWizard", "Lieu"))
        self.chk_responsable.setText(_translate("PreparationWizard", "Responsable"))
        self.chk_type_activite.setText(_translate("PreparationWizard", "Type d\'activité"))
        self.groupBox_3.setTitle(_translate("PreparationWizard", "Membre"))
        self.chk_membre.setText(_translate("PreparationWizard", "Membre"))
        self.chk_partitipante.setText(_translate("PreparationWizard", "Participante"))
        self.chk_tout.setText(_translate("PreparationWizard", "Tout sélectionner"))
        self.pgs_fin.setTitle(_translate("PreparationWizard", "Préparation complète"))
        self.pgs_fin.setSubTitle(_translate("PreparationWizard", "Le programme GUIDE est maintenant prêt pour sa première utilisation. "))
        self.plainTextEdit_2.setPlainText(_translate("PreparationWizard", "L\'assistant va maintenant compléter l\'installation du programme GUIDE."))

