# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/[C] Windows 10/Users/samueldrouin/source/repos/GUIDE-CFR/guide/interface/ui/setting.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.resize(620, 151)
        Setting.setMinimumSize(QtCore.QSize(620, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        Setting.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Setting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Setting)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(Setting)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_base_donnee = QtWidgets.QLineEdit(Setting)
        self.txt_base_donnee.setMinimumSize(QtCore.QSize(400, 0))
        self.txt_base_donnee.setReadOnly(True)
        self.txt_base_donnee.setObjectName("txt_base_donnee")
        self.horizontalLayout.addWidget(self.txt_base_donnee)
        self.btn_fichier = QtWidgets.QPushButton(Setting)
        self.btn_fichier.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Resources/Folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_fichier.setIcon(icon)
        self.btn_fichier.setIconSize(QtCore.QSize(16, 16))
        self.btn_fichier.setAutoDefault(False)
        self.btn_fichier.setFlat(False)
        self.btn_fichier.setObjectName("btn_fichier")
        self.horizontalLayout.addWidget(self.btn_fichier)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(Setting)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txt_statistique = QtWidgets.QLineEdit(Setting)
        self.txt_statistique.setMinimumSize(QtCore.QSize(400, 0))
        self.txt_statistique.setReadOnly(True)
        self.txt_statistique.setObjectName("txt_statistique")
        self.horizontalLayout_5.addWidget(self.txt_statistique)
        self.btn_statistique = QtWidgets.QPushButton(Setting)
        self.btn_statistique.setText("")
        self.btn_statistique.setIcon(icon)
        self.btn_statistique.setIconSize(QtCore.QSize(16, 16))
        self.btn_statistique.setAutoDefault(False)
        self.btn_statistique.setFlat(False)
        self.btn_statistique.setObjectName("btn_statistique")
        self.horizontalLayout_5.addWidget(self.btn_statistique)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_cancel = QtWidgets.QPushButton(Setting)
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.btn_appliquer = QtWidgets.QPushButton(Setting)
        self.btn_appliquer.setDefault(True)
        self.btn_appliquer.setObjectName("btn_appliquer")
        self.horizontalLayout_2.addWidget(self.btn_appliquer)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "Réglages"))
        self.label.setText(_translate("Setting", "Réglages"))
        self.label_2.setText(_translate("Setting", "Base de données : "))
        self.label_3.setText(_translate("Setting", "Fichier de statistiques :"))
        self.btn_cancel.setText(_translate("Setting", "Annuler"))
        self.btn_appliquer.setText(_translate("Setting", "Appliquer"))

