# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/[C] Windows 10/Users/samueldrouin/source/repos/GUIDE-CFR/guide/interface/ui/statistique.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Statistique(object):
    def setupUi(self, Statistique):
        Statistique.setObjectName("Statistique")
        Statistique.resize(800, 590)
        Statistique.setMinimumSize(QtCore.QSize(800, 590))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        Statistique.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Statistique)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Statistique)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(Statistique)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_titre = QtWidgets.QLineEdit(Statistique)
        self.txt_titre.setObjectName("txt_titre")
        self.horizontalLayout_2.addWidget(self.txt_titre)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.liste = QtWidgets.QWidget(Statistique)
        self.liste.setObjectName("liste")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.liste)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.liste)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.tbl_champs = QtWidgets.QTableWidget(self.liste)
        self.tbl_champs.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 231, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 231, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 231, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tbl_champs.setPalette(palette)
        self.tbl_champs.setAlternatingRowColors(True)
        self.tbl_champs.setObjectName("tbl_champs")
        self.tbl_champs.setColumnCount(3)
        self.tbl_champs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_champs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_champs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_champs.setHorizontalHeaderItem(2, item)
        self.tbl_champs.horizontalHeader().setDefaultSectionSize(250)
        self.tbl_champs.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tbl_champs)
        self.label_5 = QtWidgets.QLabel(self.liste)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.tbl_tri = QtWidgets.QTableWidget(self.liste)
        self.tbl_tri.setObjectName("tbl_tri")
        self.tbl_tri.setColumnCount(5)
        self.tbl_tri.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tri.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tri.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tri.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tri.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tri.setHorizontalHeaderItem(4, item)
        self.tbl_tri.horizontalHeader().setDefaultSectionSize(150)
        self.tbl_tri.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tbl_tri)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.liste)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cbx_table = QtWidgets.QComboBox(self.liste)
        self.cbx_table.setMinimumSize(QtCore.QSize(200, 0))
        self.cbx_table.setObjectName("cbx_table")
        self.horizontalLayout_3.addWidget(self.cbx_table)
        self.cbx_colonne = QtWidgets.QComboBox(self.liste)
        self.cbx_colonne.setMinimumSize(QtCore.QSize(200, 0))
        self.cbx_colonne.setObjectName("cbx_colonne")
        self.horizontalLayout_3.addWidget(self.cbx_colonne)
        self.checkBox = QtWidgets.QCheckBox(self.liste)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.liste)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.rbt_excel = QtWidgets.QRadioButton(self.liste)
        self.rbt_excel.setChecked(True)
        self.rbt_excel.setObjectName("rbt_excel")
        self.horizontalLayout_4.addWidget(self.rbt_excel)
        self.rbt_pdf = QtWidgets.QRadioButton(self.liste)
        self.rbt_pdf.setObjectName("rbt_pdf")
        self.horizontalLayout_4.addWidget(self.rbt_pdf)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.liste)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btn_annuler = QtWidgets.QPushButton(Statistique)
        self.btn_annuler.setAutoDefault(False)
        self.btn_annuler.setObjectName("btn_annuler")
        self.horizontalLayout.addWidget(self.btn_annuler)
        self.btn_enregistrer = QtWidgets.QPushButton(Statistique)
        self.btn_enregistrer.setAutoDefault(False)
        self.btn_enregistrer.setObjectName("btn_enregistrer")
        self.horizontalLayout.addWidget(self.btn_enregistrer)
        self.btn_afficher_pdf = QtWidgets.QPushButton(Statistique)
        self.btn_afficher_pdf.setAutoDefault(False)
        self.btn_afficher_pdf.setObjectName("btn_afficher_pdf")
        self.horizontalLayout.addWidget(self.btn_afficher_pdf)
        self.btn_affiche_excel = QtWidgets.QPushButton(Statistique)
        self.btn_affiche_excel.setDefault(True)
        self.btn_affiche_excel.setObjectName("btn_affiche_excel")
        self.horizontalLayout.addWidget(self.btn_affiche_excel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Statistique)
        QtCore.QMetaObject.connectSlotsByName(Statistique)

    def retranslateUi(self, Statistique):
        _translate = QtCore.QCoreApplication.translate
        Statistique.setWindowTitle(_translate("Statistique", "Statistiques"))
        self.label.setText(_translate("Statistique", "Statistiques"))
        self.label_2.setText(_translate("Statistique", "Nom de la statistique : "))
        self.label_4.setText(_translate("Statistique", "Champs : "))
        item = self.tbl_champs.horizontalHeaderItem(0)
        item.setText(_translate("Statistique", "Table"))
        item = self.tbl_champs.horizontalHeaderItem(1)
        item.setText(_translate("Statistique", "Colonne"))
        item = self.tbl_champs.horizontalHeaderItem(2)
        item.setText(_translate("Statistique", "Contrainte"))
        self.label_5.setText(_translate("Statistique", "Option de tri : "))
        item = self.tbl_tri.horizontalHeaderItem(0)
        item.setText(_translate("Statistique", "Table"))
        item = self.tbl_tri.horizontalHeaderItem(1)
        item.setText(_translate("Statistique", "Colonne"))
        item = self.tbl_tri.horizontalHeaderItem(2)
        item.setText(_translate("Statistique", "Opérateur"))
        item = self.tbl_tri.horizontalHeaderItem(3)
        item.setText(_translate("Statistique", "Valeur"))
        item = self.tbl_tri.horizontalHeaderItem(4)
        item.setText(_translate("Statistique", "Contrainte"))
        self.label_3.setText(_translate("Statistique", "Ordonner par :"))
        self.checkBox.setText(_translate("Statistique", "Décroissant"))
        self.label_6.setText(_translate("Statistique", "Fichier de sortie :"))
        self.rbt_excel.setText(_translate("Statistique", "Excel"))
        self.rbt_pdf.setText(_translate("Statistique", "PDF"))
        self.btn_annuler.setText(_translate("Statistique", "Annuler"))
        self.btn_enregistrer.setText(_translate("Statistique", "Enregistrer"))
        self.btn_afficher_pdf.setText(_translate("Statistique", "Afficher en PDF"))
        self.btn_affiche_excel.setText(_translate("Statistique", "Afficher dans Excel"))

